version: "3.9"

services:
  # postgresql database container
  db:
    container_name: sth-postgres-db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}

  # nest.js api container
  server:
    container_name: sth-api
    build: ../stairway-to-heaven
    depends_on:
      - db
    restart: unless-stopped
    #    network_mode: host
    # investigate: what this option does. It brakes things and causes error 'can't find db while connection to db
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
    ports:
      - ${API_PORT}:3001

  # angular app container
  client:
    container_name: sth-client
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - db
      - server
    restart: unless-stopped

